name: Slack Notification on Issue Update2
on:
  issues:
    types: [opened, edited, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]

jobs:
  slack_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"GitHub Issue has been updated. Action by: ${GITHUB_ACTOR}."}' $SLACK_WEBHOOK_URL
