name: Slack Notification on Issue Activity
on:
  issues:
      # types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
  issue_comment:
    # types: [created, edited, deleted]
jobs:
  slack_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          MESSAGE="GitHub Issue has been updated. Action by: \`${{ github.actor }}\`.\n"
          MESSAGE+="테스트 워크플로를 트리거한 이벤트: \`${{ github.event_name }}\`.\n"
          MESSAGE+="테스트 워크플로를 트리거한 이벤트의 데이터를 포함하는 파일의 경로: \`${{ github.event_path }}\`.\n"
          MESSAGE+="테스트 GitHub Actions 러너가 작업을 수행하는 디렉토리의 경로: \`${{ github.workspace }}\`.\n"
          MESSAGE+="테스트 트리거 이벤트에 대한 커밋 SHA: \`${{ github.sha }}\`."
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$MESSAGE\"}" $SLACK_WEBHOOK_URL
