name: Example Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Get changed files
        id: files
        run: |
          echo "::set-output name=list::$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }})"
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "attachments": [
                {
                  "color": "#36a64f",
                  "title": "커밋된 파일 경로",
                  "fields": [
                    {
                      "title": "Files",
                      "value": "https://github.com/${{ github.repository }}/tree/${{ github.sha }}/${{ steps.files.outputs.list }}",
                      "short": false
                    }
                  ]
                }
              ]
            }
    
