name: Slack Notification on Issue Activity
on:
  issues:
      # types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
  issue_comment:
    # types: [created, edited, deleted]
jobs:
  slack_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"GitHub Issue has been updated. Action by: `${{ github.actor }}`."}' $SLACK_WEBHOOK_URL
          curl -X POST -H 'Content-type: application/json' --data '{"text":"테스트 워크플로를 트리거한 이벤트:`${{ GITHUB_EVENT_NAME }}`."}' $SLACK_WEBHOOK_URL
          curl -X POST -H 'Content-type: application/json' --data '{"text":"테스트 워크플로를 트리거한 이벤트의 데이터를 포함하는 파일의 경로:`${{ GITHUB_EVENT_PATH }}`."}' $SLACK_WEBHOOK_URL
          curl -X POST -H 'Content-type: application/json' --data '{"text":"테스트 GitHub Actions 러너가 작업을 수행하는 디렉토리의 경로:`${{ GITHUB_WORKSPACE }}`."}' $SLACK_WEBHOOK_URL
          curl -X POST -H 'Content-type: application/json' --data '{"text":"테스트 트리거 이벤트에 대한 커밋 SHA:`${{ GITHUB_SHA }}`."}' $SLACK_WEBHOOK_URL
